contact_links:
  - name: Ask a question
    url: https://github.com/songkg7/o2/discussions/categories/q-a
    about: Please ask and answer questions here.
  - name: Feature request/idea
    url: https://github.com/songkg7/o2/discussions/categories/ideas
    about: All not yet well-defined feature requests must be firstly brainstormed in "feature ideas".
